### PR TITLE
Added it_IT translation

### PR DESCRIPTION
**Pull request by drAlberT**

### CODE REVIEW

**Comment by drAlberT** [comment]
@klein0r any chance to have it merged ? :)

**Comment by drAlberT** [comment]
@klein0r  ...

**Comment by drAlberT** [comment]
@mzeis @klein0r is this project alive?

**Comment by mzeis** [comment]
@drAlberT Sorry, I can't tell you. I'm not a maintainer. I only contributed some time ago.

**Comment by klein0r** [comment]
@drAlberT Sorry for the late response :) Thanks for participating

**Pull request merged**
